Fixed Solr error when deprecated cache class (follow up after upgrade to 9.2).
Error was:
revsys-nuremberg-solr-1      | 2023-08-30 02:02:26.960 ERROR (qtp557023099-21) [
x:nuremberg_dev] o.a.s.s.CacheConfig Error instantiating cache =>
org.apache.solr.common.SolrException:  Error loading class
'solr.search.LRUCache'

Follows Solr doc from:
https://solr.apache.org/guide/solr/latest/upgrade-notes/major-changes-in-solr-9.html#deprecations-and-removals

Stating that:
Legacy SolrCache implementations (LRUCache, LFUCache, FastLRUCache) have been
removed. Users have to modify their existing configurations to use CaffeineCache
instead.

Also restored highlighting algorithm to 'original' (see #309).