Rework author properties display based on user feedback
This work would improve author properties pages so both the pop-up in the
search page and the dedicated author page can configure the author properties
to:
    1- limit the amount of properties shown,
    2- limit the amount of values per properties shown,
    3- limit the amount of qualifiers, and
    4- limit the amount of values per qualifiers.

This required a reindex of the Solr records to properly store start and end
dates for "periods", and the corrresponding update of the Solr snapshot.

Relatedly, the json size of indexed author properties had to be reduced to
workaround the Solr reindexing errors such as:

Failed to add documents to Solr: Solr responded with an error (HTTP 400):
[Reason: Exception writing document id documents.document.10375 to the index;
possible analysis error: DocValuesField "authors_properties" is too large, must
be <= 32766]

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/haystack/backends/solr_backend.py", line 102, in update
    self.conn.add(docs, commit=commit, boost=index.get_field_weights())
  File "/usr/local/lib/python3.10/site-packages/pysolr.py", line 1042, in add
    return self._update(
  File "/usr/local/lib/python3.10/site-packages/pysolr.py", line 564, in _update
    return self._send_request(
  File "/usr/local/lib/python3.10/site-packages/pysolr.py", line 463, in _send_request
    raise SolrError(error_message % (resp.status_code, solr_message))

pysolr.SolrError: Solr responded with an error (HTTP 400): [Reason: Exception
writing document id documents.document.10375 to the index; possible analysis
error: DocValuesField "authors_properties" is too large, must be <= 32766]